name: Check Code Health

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js version 18.17.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.17.0
        cache: 'npm'
    - run: npm ci
    - run: npm run lint